// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3l-toIWsEHz9RGeyzGwGX7gFPIAxmAQ',
    appId: '1:87727049816:web:69905366dfc27e82af8e2d',
    messagingSenderId: '87727049816',
    projectId: 'walletcompass-project',
    authDomain: 'walletcompass-project.firebaseapp.com',
    storageBucket: 'walletcompass-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM4E_6b5ksxz698J6NoxDtgrFYBd-4TPQ',
    appId: '1:87727049816:android:7317147a58c7ed7aaf8e2d',
    messagingSenderId: '87727049816',
    projectId: 'walletcompass-project',
    storageBucket: 'walletcompass-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnxI1be6qYaaI2pQgmLgV2sFjfVfQoDbE',
    appId: '1:87727049816:ios:9a2e70f9f68bb792af8e2d',
    messagingSenderId: '87727049816',
    projectId: 'walletcompass-project',
    storageBucket: 'walletcompass-project.appspot.com',
    iosBundleId: 'com.example.copiaWalletfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnxI1be6qYaaI2pQgmLgV2sFjfVfQoDbE',
    appId: '1:87727049816:ios:9a2e70f9f68bb792af8e2d',
    messagingSenderId: '87727049816',
    projectId: 'walletcompass-project',
    storageBucket: 'walletcompass-project.appspot.com',
    iosBundleId: 'com.example.copiaWalletfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd3l-toIWsEHz9RGeyzGwGX7gFPIAxmAQ',
    appId: '1:87727049816:web:2ec469ebc7be813faf8e2d',
    messagingSenderId: '87727049816',
    projectId: 'walletcompass-project',
    authDomain: 'walletcompass-project.firebaseapp.com',
    storageBucket: 'walletcompass-project.appspot.com',
  );
}
